apiVersion: v1
kind: Secret
metadata:
  name: use-this-output
type: Opaque
data:
  ca.crt: {{ $.Values.tls.rootCA.cert }}
  {{- range $node := .Values.nodeNames -}}
  {{- $rootCA := buildCustomCert $.Values.tls.rootCA.cert $.Values.tls.rootCA.key -}}
  {{- $server := genSignedCert $node ( default nil ) (list $node) 3650 $rootCA }}
  node.{{$node}}.crt: {{ $server.Cert | b64enc }}
  node.{{$node}}.key: {{ $server.Key | b64enc }}
  {{- end }}